"""adiciona coluna contato e area

Revision ID: 4b81d19ef417
Revises: 7c92dbb2dc86
Create Date: 2021-09-29 20:34:14.381486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b81d19ef417'
down_revision = '7c92dbb2dc86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordem', sa.Column('areaConhecimento', sa.String(), nullable=True))
    op.add_column('ordem', sa.Column('contato', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordem', 'contato')
    op.drop_column('ordem', 'areaConhecimento')
    # ### end Alembic commands ###
