"""adiciona ordem

Revision ID: 7c92dbb2dc86
Revises: 
Create Date: 2021-09-28 22:49:29.545071

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7c92dbb2dc86"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ordem",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item", sa.String(), nullable=True),
        sa.Column("descricao", sa.String(), nullable=True),
        sa.Column("acao", sa.String(), nullable=True),
        sa.Column("tipo", sa.String(), nullable=True),
        sa.Column("data_publicacao", sa.Date(), nullable=True),
        sa.Column("data_validade", sa.Date(), nullable=True),
        sa.Column("nomeInst", sa.Date(), nullable=True),
        sa.Column("emprestimo", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ordem")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ordem")
    # ### end Alembic commands ###
