"""tabelas

Revision ID: 8dfa80002549
Revises: 
Create Date: 2021-10-25 20:47:28.994640

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8dfa80002549"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "instituicao",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.String(), nullable=True),
        sa.Column("endereco", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instituicao")),
    )
    op.create_table(
        "usuario",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("contato", sa.String(), nullable=True),
        sa.Column("id_inst", sa.Integer(), sa.ForeignKey("instituicao.id"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usuario")),
    )
    op.create_table(
        "ordem",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item", sa.String(), nullable=True),
        sa.Column("descricao", sa.String(), nullable=True),
        sa.Column("acao", sa.String(), nullable=True),
        sa.Column("tipo", sa.String(), nullable=True),
        sa.Column("data_publicacao", sa.Date(), nullable=True),
        sa.Column("data_validade", sa.Date(), nullable=True),
        sa.Column("emprestimo", sa.Boolean(), nullable=True),
        sa.Column("area_conhecimento", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True, default="DISPONIVEL"),
        sa.Column("quantidade", sa.String(), nullable=True),
        sa.Column("id_usuario", sa.Integer(), sa.ForeignKey("usuario.id"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ordem")),
    )
    op.create_table(
        "negocio",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_ordem", sa.Integer(), sa.ForeignKey("ordem.id"), nullable=False),
        sa.Column("id_solicitante", sa.Integer(), sa.ForeignKey("usuario.id"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_negocio")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("negocio")
    op.drop_table("ordem")
    op.drop_table("usuario")
    op.drop_table("instituicao")
    # ### end Alembic commands ###
